data_dir: "./data/"
db_engine_url: "postgresql://postgres:ColynX360@localhost:5432/daas"
table_names:
    - table_one
    - table_two
    - table_three
distance_from_event: 5.0
lat_default: 1.2921
lon_default: 36.8219