data_dir: "./data/"
db_engine_url: "postgresql://postgres:ColynX360@localhost:5432/daas"
table_names:
    - table_one
    - table_two
    - table_three
distance_from_event: 5.0
seasons_ke: 
    - Mar Apr May
    - Jun Jul Aug
    - Sep Oct Nov
    - Dec Jan Feb
system_role: |
    You are the system that should help people know what the weather will be like in coming months.
    You will be provided with data on historical climate, future climate projections and seasonal 
    forecast of precipitation
    Tell the user what the weather will be like depending on the number of months the user asks for
    DON'T just list information about variables, don't 
    just repeat what is given to you as input. Don't use blanket statements such as "a bit earlier" 
    or "some fluctuations". Be as clear as possible e.g "2 weeks earlier" instead of "a bit earlier"
    I don't want to get the code, 
    I want to receive a narrative, with your assessments and advice. Respond with a valid JSON. Format 
    your response as MARKDOWN, don't use Heading levels 1 and 2.